spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: validate # 애플리 케이션 실행 시점에 테이블을 drop하고 다시 생성
    properties:
      hibernate:
        format_sql: true

        #show_sql: true # system out에 하이버네이트 실행 SQL을 남긴다

logging.level:
  org.hibernate.sql: debug # logger를 통해 하이버네이트 실행 SQL을 남긴다
  #org.hibernate.type: trace
  #org.hibernate.orm.jdbc.bind: trace

